"""PyVax Transformer — Python AST → Flattened Solidity Source Code.

Converts a ContractState (from PythonASTAnalyzer) into verified-ready,
single-file Solidity source that can be compiled with solc and verified
on Snowtrace/Etherscan.

Usage:
    from avax_cli.transpiler import PythonASTAnalyzer
    from avax_cli.transformer import generate_solidity, python_to_verified_solidity

    # Option A: From ContractState
    state = PythonASTAnalyzer().analyze_contract(python_source)
    sol_source = generate_solidity(state, contract_name="MyToken")

    # Option B: Full pipeline
    result = python_to_verified_solidity(python_source)
    print(result["solidity"])  # Flattened .sol
    print(result["abi"])       # JSON ABI
"""

from __future__ import annotations

import ast
import re
import textwrap
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from rich.console import Console

from .transpiler import (
    ContractState,
    PythonASTAnalyzer,
    PYVAX_ACTION_DECORATORS,
    PYVAX_VIEW_DECORATORS,
    _validate_ast_sandbox,
)

console = Console()

# ── Solidity type mapping ─────────────────────────────────────────────

PYTHON_TO_SOL_TYPE = {
    "uint256": "uint256",
    "int": "uint256",
    "address": "address",
    "str": "address",
    "bool": "bool",
    "mapping": "mapping(address => uint256)",
    "string": "string",
}

# Default Solidity version for output
SOL_VERSION = "0.8.24"
SOL_LICENSE = "MIT"


# ── Result dataclass ──────────────────────────────────────────────────


@dataclass
class VerifiedContract:
    """Result of Python → Verified Solidity transformation."""
    solidity: str              # Flattened .sol source
    abi: List[Dict[str, Any]]  # JSON ABI
    contract_name: str         # Solidity contract name
    compiler_version: str = f"v{SOL_VERSION}"
    optimization_runs: int = 200
    evm_version: str = "paris"


# ── Solidity Code Generator ──────────────────────────────────────────


def _extract_class_info(python_source: str) -> Dict[str, Any]:
    """Independently parse Python source to extract class-level info.

    The PythonASTAnalyzer has limitations:
    - It doesn't store __init__ in the functions dict
    - visit_Assign inside functions overrides initial_values
    - Empty string annotations get their type overridden to uint256

    This function provides ground-truth values by parsing the AST directly.
    """
    tree = ast.parse(python_source)
    info: Dict[str, Any] = {
        "annotation_types": {},   # var_name → Python annotation (int/str/dict/bool)
        "class_defaults": {},     # var_name → default value from class body
        "constructor_body": None, # AST body nodes for __init__
    }

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue

        for item in node.body:
            # Class-level annotated assignment: owner: str = ""
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                var_name = item.target.id
                # Store the annotation type string
                if isinstance(item.annotation, ast.Name):
                    info["annotation_types"][var_name] = item.annotation.id
                # Store the true class-level default
                if item.value is not None:
                    if isinstance(item.value, ast.Constant):
                        info["class_defaults"][var_name] = item.value.value
                    elif isinstance(item.value, ast.Dict):
                        info["class_defaults"][var_name] = {}

            # Constructor: def __init__(self)
            if isinstance(item, ast.FunctionDef) and item.name == "__init__":
                info["constructor_body"] = item.body

        break  # Only process first class

    return info


class SolidityGenerator:
    """Converts a ContractState into flattened Solidity source code."""

    def __init__(
        self,
        state: ContractState,
        contract_name: str = "PyVaxContract",
        class_info: Optional[Dict[str, Any]] = None,
    ):
        self.state = state
        self.contract_name = contract_name
        self._indent = 0
        self._lines: List[str] = []
        # Track events so we can declare them
        self._events: Dict[str, List[str]] = {}
        # Store the original Python AST for body translation
        self._func_infos = state.functions
        # Extra class-level info from independent parsing
        self._class_info = class_info or {}

    def generate(self) -> str:
        """Generate complete Solidity source."""
        # Collect events from function bodies
        self._collect_events()

        # Header
        self._emit(f"// SPDX-License-Identifier: {SOL_LICENSE}")
        self._emit(f"// Generated by PyVax Transformer — Python to Verified Solidity")
        self._emit(f"// https://pyvax.xyz")
        self._emit(f"pragma solidity ^{SOL_VERSION};")
        self._emit("")
        self._emit(f"contract {self.contract_name} {{")
        self._indent += 1

        # State variables
        self._gen_state_vars()
        self._emit("")

        # Events
        self._gen_events()

        # Constructor (if __init__ exists)
        self._gen_constructor()

        # Functions
        self._gen_functions()

        self._indent -= 1
        self._emit("}")
        self._emit("")

        return "\n".join(self._lines)

    # ── Output helpers ────────────────────────────────────────────────

    def _emit(self, line: str = "", end: bool = False) -> None:
        if line.strip() == "":
            self._lines.append("")
        elif end:
            # Append to existing line (for else-if chaining)
            if self._lines:
                self._lines[-1] += line
            else:
                self._lines.append("    " * self._indent + line)
        else:
            self._lines.append("    " * self._indent + line)

    # ── State Variables ───────────────────────────────────────────────

    def _gen_state_vars(self) -> None:
        for var_name, slot in sorted(self.state.variables.items(), key=lambda x: x[1]):
            sol_type = self._var_type(var_name)
            # Use class-level defaults (not analyzer's which get overwritten)
            init_val = self._class_info.get("class_defaults", {}).get(
                var_name, self.state.initial_values.get(var_name)
            )

            if sol_type.startswith("mapping"):
                self._emit(f"{sol_type} public {self._sol_name(var_name)};")
            elif init_val is not None and init_val != 0 and init_val != "" and init_val is not False and init_val != {}:
                if sol_type == "address":
                    if isinstance(init_val, int) and init_val > 0:
                        self._emit(f"{sol_type} public {self._sol_name(var_name)} = address(0x{init_val:040x});")
                    else:
                        self._emit(f"{sol_type} public {self._sol_name(var_name)};")
                elif sol_type == "bool":
                    self._emit(f"{sol_type} public {self._sol_name(var_name)} = {str(init_val).lower()};")
                else:
                    self._emit(f"{sol_type} public {self._sol_name(var_name)} = {init_val};")
            else:
                self._emit(f"{sol_type} public {self._sol_name(var_name)};")

    def _var_type(self, var_name: str) -> str:
        """Get Solidity type for a state variable.

        Prioritises the annotation type from independent parsing over
        the analyzer's type which can be wrong (e.g. str="" → uint256).
        """
        # Check independent annotation first
        ann = self._class_info.get("annotation_types", {}).get(var_name)
        if ann == "str":
            return "address"
        if ann == "dict":
            mapping_info = self.state.mappings.get(var_name, {})
            key_t = PYTHON_TO_SOL_TYPE.get(mapping_info.get("key_type", "address"), "address")
            val_t = PYTHON_TO_SOL_TYPE.get(mapping_info.get("value_type", "uint256"), "uint256")
            return f"mapping({key_t} => {val_t})"
        if ann == "bool":
            return "bool"

        # Fall back to analyzer's type
        vtype = self.state.variable_types.get(var_name, "uint256")
        if vtype == "mapping":
            mapping_info = self.state.mappings.get(var_name, {})
            key_t = PYTHON_TO_SOL_TYPE.get(mapping_info.get("key_type", "address"), "address")
            val_t = PYTHON_TO_SOL_TYPE.get(mapping_info.get("value_type", "uint256"), "uint256")
            return f"mapping({key_t} => {val_t})"
        return PYTHON_TO_SOL_TYPE.get(vtype, "uint256")

    def _sol_name(self, name: str) -> str:
        """Convert Python snake_case to camelCase for Solidity."""
        # Keep snake_case — it's valid Solidity and preserves readability
        return name

    # ── Events ────────────────────────────────────────────────────────

    def _collect_events(self) -> None:
        """Walk function bodies to find all self.emit() calls."""
        for func_name, func_info in self._func_infos.items():
            body = func_info.get("body", [])
            for node in self._walk_ast_list(body):
                if (isinstance(node, ast.Call)
                        and isinstance(node.func, ast.Attribute)
                        and isinstance(node.func.value, ast.Name)
                        and node.func.value.id == "self"
                        and node.func.attr == "emit"
                        and node.args
                        and isinstance(node.args[0], ast.Constant)
                        and isinstance(node.args[0].value, str)):
                    event_name = node.args[0].value
                    if event_name not in self._events:
                        param_types = []
                        for i, arg in enumerate(node.args[1:]):
                            # Infer type from context
                            param_types.append(self._infer_event_param_type(arg, func_info))
                        self._events[event_name] = param_types

    def _infer_event_param_type(self, node: ast.AST, func_info: dict) -> str:
        """Infer Solidity type for an event parameter from its AST."""
        if isinstance(node, ast.Constant):
            if isinstance(node.value, int):
                if node.value == 0:
                    return "address"  # address(0) pattern
                return "uint256"
        if isinstance(node, ast.Name):
            # Check function params
            if node.id in func_info.get("args", []):
                idx = func_info["args"].index(node.id)
                if idx < len(func_info.get("param_types", [])):
                    return func_info["param_types"][idx]
            return "uint256"
        if isinstance(node, ast.Attribute):
            if isinstance(node.value, ast.Name) and node.value.id == "self":
                var_type = self.state.variable_types.get(node.attr, "uint256")
                return PYTHON_TO_SOL_TYPE.get(var_type, "uint256")
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Attribute) and node.func.attr == "msg_sender":
                return "address"
        # Binary ops are uint256
        if isinstance(node, ast.BinOp):
            return "uint256"
        return "uint256"

    def _gen_events(self) -> None:
        if not self._events:
            return
        for event_name, param_types in self._events.items():
            params = []
            for i, ptype in enumerate(param_types):
                sol_type = PYTHON_TO_SOL_TYPE.get(ptype, ptype)
                # First address param is indexed for Transfer-like events
                indexed = " indexed" if sol_type == "address" and i < 2 else ""
                params.append(f"{sol_type}{indexed} param{i}")
            self._emit(f"event {event_name}({', '.join(params)});")
        self._emit("")

    # ── Constructor ───────────────────────────────────────────────────

    def _gen_constructor(self) -> None:
        # Try functions dict first, then fall back to independent parse
        init_info = self._func_infos.get("__init__")
        body = None
        if init_info:
            body = init_info.get("body", [])
        elif self._class_info.get("constructor_body"):
            body = self._class_info["constructor_body"]
            init_info = {"args": [], "param_types": []}  # dummy for gen_statement

        if body is None:
            return

        self._emit("constructor() {")
        self._indent += 1
        for stmt in body:
            self._gen_statement(stmt, init_info)
        self._indent -= 1
        self._emit("}")
        self._emit("")

    # ── Functions ─────────────────────────────────────────────────────

    def _gen_functions(self) -> None:
        for func_name, func_info in self._func_infos.items():
            if func_name == "__init__":
                continue

            # Build parameters
            params = []
            for arg_name, arg_type in zip(
                func_info.get("args", []),
                func_info.get("param_types", [])
            ):
                sol_type = PYTHON_TO_SOL_TYPE.get(arg_type, "uint256")
                params.append(f"{sol_type} {self._sol_name(arg_name)}")

            param_str = ", ".join(params)

            # Visibility + mutability
            if func_info.get("is_view"):
                mutability = "external view"
            else:
                mutability = "external"

            # Return type
            returns = ""
            if func_info.get("has_return") and func_info.get("return_type"):
                ret_type = PYTHON_TO_SOL_TYPE.get(func_info["return_type"], func_info["return_type"])
                returns = f" returns ({ret_type})"

            # Function signature
            self._emit(f"function {self._sol_name(func_name)}({param_str}) {mutability}{returns} {{")
            self._indent += 1

            # Function body
            for stmt in func_info.get("body", []):
                self._gen_statement(stmt, func_info)

            self._indent -= 1
            self._emit("}")
            self._emit("")

    # ── Statement Translation ─────────────────────────────────────────

    def _gen_statement(self, node: ast.AST, func_info: dict) -> None:
        """Translate a Python AST statement to Solidity."""

        if isinstance(node, ast.Assign):
            self._gen_assign(node, func_info)

        elif isinstance(node, ast.Expr):
            if isinstance(node.value, ast.Call):
                self._gen_call_stmt(node.value, func_info)

        elif isinstance(node, ast.Return):
            if node.value:
                self._emit(f"return {self._gen_expr(node.value, func_info)};")
            else:
                self._emit("return;")

        elif isinstance(node, ast.If):
            self._gen_if(node, func_info)

        elif isinstance(node, ast.While):
            cond = self._gen_expr(node.test, func_info)
            self._emit(f"while ({cond}) {{")
            self._indent += 1
            for stmt in node.body:
                self._gen_statement(stmt, func_info)
            self._indent -= 1
            self._emit("}")

        elif isinstance(node, ast.For):
            self._gen_for(node, func_info)

        elif isinstance(node, ast.Pass):
            pass  # No-op

        elif isinstance(node, ast.AugAssign):
            target = self._gen_expr(node.target, func_info)
            value = self._gen_expr(node.value, func_info)
            op = self._binop_symbol(node.op)
            self._emit(f"{target} {op}= {value};")

    def _gen_assign(self, node: ast.Assign, func_info: dict) -> None:
        """Translate assignment statement."""
        if len(node.targets) != 1:
            return

        target = node.targets[0]
        value = self._gen_expr(node.value, func_info)

        if isinstance(target, ast.Attribute):
            if isinstance(target.value, ast.Name) and target.value.id == "self":
                self._emit(f"{self._sol_name(target.attr)} = {value};")
            else:
                self._emit(f"{self._gen_expr(target, func_info)} = {value};")
        elif isinstance(target, ast.Subscript):
            target_str = self._gen_expr(target, func_info)
            self._emit(f"{target_str} = {value};")
        elif isinstance(target, ast.Name):
            # Local variable
            sol_type = self._infer_expr_type(node.value, func_info)
            self._emit(f"{sol_type} {target.id} = {value};")

    def _gen_call_stmt(self, call: ast.Call, func_info: dict) -> None:
        """Translate a call statement (e.g., self.require, self.emit)."""
        if isinstance(call.func, ast.Attribute):
            if isinstance(call.func.value, ast.Name) and call.func.value.id == "self":
                method = call.func.attr

                if method == "require":
                    if len(call.args) >= 2 and isinstance(call.args[1], ast.Constant):
                        cond = self._gen_expr(call.args[0], func_info)
                        msg = call.args[1].value
                        self._emit(f'require({cond}, "{msg}");')
                    elif call.args:
                        cond = self._gen_expr(call.args[0], func_info)
                        self._emit(f"require({cond});")

                elif method == "emit":
                    if call.args and isinstance(call.args[0], ast.Constant):
                        event_name = call.args[0].value
                        params = [self._gen_expr(a, func_info) for a in call.args[1:]]
                        self._emit(f"emit {event_name}({', '.join(params)});")

                else:
                    # Other self.method() calls
                    params = [self._gen_expr(a, func_info) for a in call.args]
                    self._emit(f"{method}({', '.join(params)});")

    def _gen_if(self, node: ast.If, func_info: dict) -> None:
        """Translate if/elif/else."""
        cond = self._gen_expr(node.test, func_info)
        self._emit(f"if ({cond}) {{")
        self._indent += 1
        for stmt in node.body:
            self._gen_statement(stmt, func_info)
        self._indent -= 1

        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
                self._emit("} else ", end=True)
                self._gen_if(node.orelse[0], func_info)
                return
            else:
                self._emit("} else {")
                self._indent += 1
                for stmt in node.orelse:
                    self._gen_statement(stmt, func_info)
                self._indent -= 1
        self._emit("}")

    def _gen_for(self, node: ast.For, func_info: dict) -> None:
        """Translate simple range-based for loops."""
        # for i in range(n) → for (uint256 i = 0; i < n; i++)
        if (isinstance(node.iter, ast.Call)
                and isinstance(node.iter.func, ast.Name)
                and node.iter.func.id == "range"
                and isinstance(node.target, ast.Name)):
            var = node.target.id
            if len(node.iter.args) == 1:
                limit = self._gen_expr(node.iter.args[0], func_info)
                self._emit(f"for (uint256 {var} = 0; {var} < {limit}; {var}++) {{")
            elif len(node.iter.args) >= 2:
                start = self._gen_expr(node.iter.args[0], func_info)
                limit = self._gen_expr(node.iter.args[1], func_info)
                self._emit(f"for (uint256 {var} = {start}; {var} < {limit}; {var}++) {{")
            else:
                self._emit("// Unsupported for loop")
                return

            self._indent += 1
            for stmt in node.body:
                self._gen_statement(stmt, func_info)
            self._indent -= 1
            self._emit("}")
        else:
            self._emit("// Unsupported for loop — only range() is supported")

    # ── Expression Translation ────────────────────────────────────────

    def _gen_expr(self, node: ast.AST, func_info: dict) -> str:
        """Translate a Python expression to Solidity."""

        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if isinstance(node.value, int):
                return str(node.value)
            if isinstance(node.value, str):
                # Empty string → address(0)
                if node.value == "":
                    return "address(0)"
                # Hex address
                if node.value.startswith("0x") and len(node.value) == 42:
                    return node.value
                return f'"{node.value}"'
            return str(node.value)

        if isinstance(node, ast.Name):
            if node.id == "True":
                return "true"
            if node.id == "False":
                return "false"
            return node.id

        if isinstance(node, ast.Attribute):
            if isinstance(node.value, ast.Name) and node.value.id == "self":
                return self._sol_name(node.attr)
            return f"{self._gen_expr(node.value, func_info)}.{node.attr}"

        if isinstance(node, ast.Subscript):
            return self._gen_subscript(node, func_info)

        if isinstance(node, ast.BinOp):
            left = self._gen_expr(node.left, func_info)
            right = self._gen_expr(node.right, func_info)
            op = self._binop_symbol(node.op)
            return f"{left} {op} {right}"

        if isinstance(node, ast.UnaryOp):
            operand = self._gen_expr(node.operand, func_info)
            if isinstance(node.op, ast.Not):
                return f"!{operand}"
            if isinstance(node.op, ast.USub):
                return f"-{operand}"
            return operand

        if isinstance(node, ast.BoolOp):
            op = " && " if isinstance(node.op, ast.And) else " || "
            parts = [self._gen_expr(v, func_info) for v in node.values]
            return op.join(parts)

        if isinstance(node, ast.Compare):
            left = self._gen_expr(node.left, func_info)
            parts = [left]
            for op, comp in zip(node.ops, node.comparators):
                parts.append(self._cmpop_symbol(op))
                parts.append(self._gen_expr(comp, func_info))
            return " ".join(parts)

        if isinstance(node, ast.Call):
            return self._gen_call_expr(node, func_info)

        if isinstance(node, ast.IfExp):
            test = self._gen_expr(node.test, func_info)
            body = self._gen_expr(node.body, func_info)
            orelse = self._gen_expr(node.orelse, func_info)
            return f"({test} ? {body} : {orelse})"

        return "/* unsupported expr */"

    def _gen_subscript(self, node: ast.Subscript, func_info: dict) -> str:
        """Translate subscript (mapping access)."""
        value = self._gen_expr(node.value, func_info)
        if isinstance(node.slice, ast.Index):
            # Python 3.8 compatibility
            idx = self._gen_expr(node.slice.value, func_info)
        else:
            idx = self._gen_expr(node.slice, func_info)
        return f"{value}[{idx}]"

    def _gen_call_expr(self, node: ast.Call, func_info: dict) -> str:
        """Translate function calls used as expressions."""
        if isinstance(node.func, ast.Attribute):
            if isinstance(node.func.value, ast.Name) and node.func.value.id == "self":
                method = node.func.attr
                if method == "msg_sender":
                    return "msg.sender"
                if method == "msg_value":
                    return "msg.value"
                if method == "balance":
                    return "address(this).balance"
                # self.mapping.get(key, default) → mapping[key]
                args = [self._gen_expr(a, func_info) for a in node.args]
                return f"{method}({', '.join(args)})"

            # self.mapping.get(key, default) → mapping[key]
            if (isinstance(node.func.value, ast.Attribute)
                    and isinstance(node.func.value.value, ast.Name)
                    and node.func.value.value.id == "self"
                    and node.func.attr == "get"):
                mapping_name = node.func.value.attr
                if node.args:
                    key = self._gen_expr(node.args[0], func_info)
                    return f"{self._sol_name(mapping_name)}[{key}]"

        if isinstance(node.func, ast.Name):
            func_name = node.func.id
            if func_name == "int":
                if node.args:
                    return self._gen_expr(node.args[0], func_info)
                return "0"
            if func_name == "bool":
                if node.args:
                    return self._gen_expr(node.args[0], func_info)
                return "false"
            args = [self._gen_expr(a, func_info) for a in node.args]
            return f"{func_name}({', '.join(args)})"

        return "/* unsupported call */"

    # ── Operator symbols ──────────────────────────────────────────────

    @staticmethod
    def _binop_symbol(op: ast.AST) -> str:
        return {
            ast.Add: "+", ast.Sub: "-", ast.Mult: "*",
            ast.Div: "/", ast.Mod: "%", ast.Pow: "**",
            ast.BitAnd: "&", ast.BitOr: "|", ast.BitXor: "^",
            ast.LShift: "<<", ast.RShift: ">>",
        }.get(type(op), "+")

    @staticmethod
    def _cmpop_symbol(op: ast.AST) -> str:
        return {
            ast.Eq: "==", ast.NotEq: "!=",
            ast.Lt: "<", ast.LtE: "<=",
            ast.Gt: ">", ast.GtE: ">=",
        }.get(type(op), "==")

    def _infer_expr_type(self, node: ast.AST, func_info: dict) -> str:
        """Infer Solidity type of an expression for local var declarations."""
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Attribute):
                if node.func.attr == "msg_sender":
                    return "address"
        if isinstance(node, ast.Attribute):
            if isinstance(node.value, ast.Name) and node.value.id == "self":
                vtype = self.state.variable_types.get(node.attr, "uint256")
                return PYTHON_TO_SOL_TYPE.get(vtype, "uint256")
        return "uint256"

    # ── AST helpers ───────────────────────────────────────────────────

    @staticmethod
    def _walk_ast_list(nodes: List[ast.AST]):
        """Walk all nodes in a list of AST nodes."""
        for node in nodes:
            yield from ast.walk(node)


# ── Public API ────────────────────────────────────────────────────────


def generate_solidity(
    state: ContractState,
    contract_name: str = "PyVaxContract",
    python_source: Optional[str] = None,
) -> str:
    """Generate flattened Solidity source from a ContractState.

    Args:
        state: Result of PythonASTAnalyzer.analyze_contract()
        contract_name: Name for the Solidity contract
        python_source: Original Python source for accurate type/default extraction

    Returns:
        Complete Solidity source code string
    """
    class_info = _extract_class_info(python_source) if python_source else None
    gen = SolidityGenerator(state, contract_name, class_info=class_info)
    return gen.generate()


def generate_abi_from_state(
    state: ContractState,
    python_source: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Generate standard JSON ABI from a ContractState.

    This mirrors what the existing transpiler produces but is independent,
    suitable for use alongside the Solidity source.
    """
    abi: List[Dict[str, Any]] = []

    # Constructor — check functions dict; also check via source parse
    has_constructor = "__init__" in state.functions
    if not has_constructor and python_source:
        # The analyzer doesn't always store __init__ in functions
        tree = ast.parse(python_source)
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "__init__":
                has_constructor = True
                break

    if has_constructor:
        init = state.functions.get("__init__", {})
        abi.append({
            "type": "constructor",
            "inputs": [
                {"name": n, "type": t}
                for n, t in zip(init.get("args", []), init.get("param_types", []))
            ],
            "stateMutability": "nonpayable",
        })

    # Functions
    for func_name, info in state.functions.items():
        if func_name == "__init__":
            continue

        mutability = "view" if info.get("is_view") else "nonpayable"
        entry: Dict[str, Any] = {
            "type": "function",
            "name": func_name,
            "inputs": [
                {"name": n, "type": PYTHON_TO_SOL_TYPE.get(t, t)}
                for n, t in zip(info.get("args", []), info.get("param_types", []))
            ],
            "outputs": [],
            "stateMutability": mutability,
        }
        if info.get("has_return") and info.get("return_type"):
            ret_type = PYTHON_TO_SOL_TYPE.get(info["return_type"], info["return_type"])
            entry["outputs"] = [{"name": "", "type": ret_type}]
        abi.append(entry)

    return abi


def python_to_verified_solidity(
    python_source: str,
    contract_name: Optional[str] = None,
) -> Dict[str, Any]:
    """Full pipeline: Python source → VerifiedContract dict.

    Args:
        python_source: Python smart contract source code
        contract_name: Optional name override (auto-detected from class name)

    Returns:
        Dict with keys: solidity, abi, contract_name, compiler_version,
        optimization_runs, evm_version
    """
    # Sandbox validation
    _validate_ast_sandbox(python_source)

    # Analyze
    analyzer = PythonASTAnalyzer()
    state = analyzer.analyze_contract(python_source)

    # Auto-detect contract name from Python class
    if contract_name is None:
        tree = ast.parse(python_source)
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                contract_name = node.name
                break
        if contract_name is None:
            contract_name = "PyVaxContract"

    console.print(f"[bold cyan]Generating Solidity for: {contract_name}[/bold cyan]")

    # Generate Solidity (pass source for accurate type/default extraction)
    sol_source = generate_solidity(state, contract_name, python_source=python_source)

    # Generate ABI (pass source for constructor detection)
    abi = generate_abi_from_state(state, python_source=python_source)

    console.print(f"[green]Solidity generated:[/green] {len(sol_source)} chars, {len(abi)} ABI entries")

    return {
        "solidity": sol_source,
        "abi": abi,
        "contract_name": contract_name,
        "compiler_version": f"v{SOL_VERSION}",
        "optimization_runs": 200,
        "evm_version": "paris",
    }
